const POSE_NOSE_RAW_INDEX = 0;
const POSE_LEFT_SHOULDER_RAW_INDEX = 11;
const POSE_RIGHT_SHOULDER_RAW_INDEX = 12;
const POSE_LEFT_HIP_RAW_INDEX = 23;
const POSE_RIGHT_HIP_RAW_INDEX = 24;

export const POSE_LANDMARK_SUBSET = [
  POSE_NOSE_RAW_INDEX,
  POSE_LEFT_SHOULDER_RAW_INDEX,
  POSE_RIGHT_SHOULDER_RAW_INDEX,
  POSE_LEFT_HIP_RAW_INDEX,
  POSE_RIGHT_HIP_RAW_INDEX,
];

export const POSE_SUBSET_NOSE = 0;
export const POSE_SUBSET_LEFT_SHOULDER = 1;
export const POSE_SUBSET_RIGHT_SHOULDER = 2;
export const POSE_SUBSET_LEFT_HIP = 3;
export const POSE_SUBSET_RIGHT_HIP = 4;
